server:
  port: 8089
spring:
  datasource:

    # jdbc:h2:tcp//localhost/〜/test 远程连接
    # jdbc:h2:〜/test 嵌入式配置
    # jdbc:h2:mem:test 内存存储
    url: jdbc:h2:~/test;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
