server:
  port: 15671
spring:
  rabbitmq:
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /
    host: 192.168.56.11
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2
          max-attempts: 3
          stateless: true
