server:
  port: 8080

spring:
  application:
    #服务名称
    name: authorization-server
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #mysql驱动8.x版本使用com.mysql.cj.jdbc.Driver
    #5.x使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库地址
    url: jdbc:mysql://192.168.245.100:3306/auth2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #数据库账号
    username: root
    #数据库密码
    password: root
    #hikari连接池
    hikari:
      #2*cpu
      maximum-pool-size: 16
      #cpu
      minimum-idle: 8
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  redis:
    port: 6379
    host: 192.168.245.100
    database: 0
