#spring:
#  redis:
#    database: 0
#    host: 192.168.245.100
#    port: 6379
#    password:
#    jedis:
#      pool:
#        min-idle: 0
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#    connect-timeout: 30000ms
